title: Xiaohang Tang
position: PhD Student
affiliation: Virginia Tech
email: xiaohangtang@vt.edu
keywords: Xiaohang Tang
google_scholar:
github_link:
linkedin: 
avatar: ./assets/img/avatar.png
google_analytics: UA-215537727-1
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png
description: 
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
